source 'http://rubygems.org'

gem 'jeweler'
gem 'rspec', '~> 2.6.0'
gem 'yard'

gem 'tilt', '~> 1.3.3'
gem 'mustache', '~> 0.99.4'
gem 'builder'
gem 'watch'
gem 'sinatra'
gem 'maruku'
gem 'less'
gem 'launchy'
gem 'activesupport'
gem 'i18n'
